gameTime: 100

points:
  home: 1
  neutral: 2
  enemy: 3
  diseased: -2

objects:
  healthyHives:
    - 9
    - 22
    - 27
    - 29
    - 36
    - 40
    - 43
    - 47
  diseasedHives:
    - 10
    - 24
    - 30
    - 42

robots:
  0: Acvirki
  2: Unicode Abuse
  5: Razhroščevalci
  12: Domen^3
  14: Bee#
  18: Zero Latency
  19: Pršut in teran
  25: LASPP
  32: Remove Support
  33: Electric Boogaloo
  35: Kolebnica
  39: the-org
  41: Cloud

